# Generated by Django 5.2.6 on 2025-09-03 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'NSE', 'BSE'", max_length=50, unique=True
                    ),
                ),
                ("currency", models.CharField(help_text="e.g., 'INR'", max_length=10)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ticker",
                    models.CharField(help_text="e.g., 'RELIANCE'", max_length=20),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Reliance Industries'", max_length=255
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="securities", to="core.category"
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="securities",
                        to="securities.exchange",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Securities",
                "unique_together": {("exchange", "ticker")},
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=500, unique=True)),
                ("headline", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("published_at", models.DateTimeField()),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("sentiment_details", models.JSONField(blank=True, null=True)),
                (
                    "security",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_articles",
                        to="securities.security",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="CorporateAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ex_date", models.DateField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("DIVIDEND", "Dividend"),
                            ("SPLIT", "Split"),
                            ("BONUS", "Bonus"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        help_text="e.g., {'ratio': '1:2'} or {'dividend_per_share': 5.0}"
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_actions",
                        to="securities.security",
                    ),
                ),
            ],
            options={
                "ordering": ["-ex_date"],
            },
        ),
        migrations.CreateModel(
            name="SecurityPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("open", models.DecimalField(decimal_places=4, max_digits=12)),
                ("high", models.DecimalField(decimal_places=4, max_digits=12)),
                ("low", models.DecimalField(decimal_places=4, max_digits=12)),
                ("close", models.DecimalField(decimal_places=4, max_digits=12)),
                ("adj_close", models.DecimalField(decimal_places=4, max_digits=12)),
                ("volume", models.BigIntegerField()),
                (
                    "sma_20",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "sma_50",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "sma_200",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "rsi",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "macd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "bollinger_upper",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "bollinger_lower",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="securities.security",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("security", "date")},
            },
        ),
    ]
