# Generated by Django 5.2.6 on 2025-09-03 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("securities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityPriceIntraday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("datetime", models.DateTimeField()),
                ("open", models.DecimalField(decimal_places=4, max_digits=12)),
                ("high", models.DecimalField(decimal_places=4, max_digits=12)),
                ("low", models.DecimalField(decimal_places=4, max_digits=12)),
                ("close", models.DecimalField(decimal_places=4, max_digits=12)),
                ("volume", models.BigIntegerField()),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intraday_prices",
                        to="securities.security",
                    ),
                ),
            ],
            options={
                "ordering": ["-datetime"],
                "unique_together": {("security", "datetime")},
            },
        ),
    ]
