# Generated by Django 5.2.6 on 2025-09-03 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("securities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_name",
                    models.CharField(
                        choices=[("ARIMA", "ARIMA"), ("LSTM", "LSTM")], max_length=10
                    ),
                ),
                (
                    "prediction_date",
                    models.DateField(
                        help_text="The date for which the prediction is made"
                    ),
                ),
                (
                    "predicted_value",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "prediction_made_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the prediction was generated"
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="securities.security",
                    ),
                ),
            ],
            options={
                "ordering": ["-prediction_date"],
                "unique_together": {("security", "model_name", "prediction_date")},
            },
        ),
    ]
