# Generated by Django 5.2.6 on 2025-09-03 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutualFundHouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'HDFC Mutual Fund'",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MutualFundScheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheme_code",
                    models.IntegerField(
                        help_text="AMFI's unique scheme code", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "isin",
                    models.CharField(
                        help_text="ISIN for the scheme", max_length=20, unique=True
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="schemes", to="core.category"
                    ),
                ),
                (
                    "fund_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="mutual_funds.mutualfundhouse",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MutualFundNAV",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "nav",
                    models.DecimalField(
                        decimal_places=4, help_text="Net Asset Value", max_digits=12
                    ),
                ),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navs",
                        to="mutual_funds.mutualfundscheme",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("scheme", "date")},
            },
        ),
    ]
