# Generated by Django 5.2.6 on 2025-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mutual_funds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutualfundscheme",
            name="scheme_code",
            field=models.IntegerField(help_text="AMFI's scheme code"),
        ),
    ]
