# Generated by Django 5.2.6 on 2025-09-03 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mutual_funds", "0002_alter_mutualfundscheme_scheme_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="MutualFundPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "return_1y",
                    models.FloatField(
                        blank=True, help_text="1-Year Annualized Return", null=True
                    ),
                ),
                (
                    "return_3y",
                    models.FloatField(
                        blank=True, help_text="3-Year Annualized Return", null=True
                    ),
                ),
                (
                    "return_5y",
                    models.FloatField(
                        blank=True, help_text="5-Year Annualized Return", null=True
                    ),
                ),
                (
                    "ytd_return",
                    models.FloatField(
                        blank=True, help_text="Year-to-Date Return", null=True
                    ),
                ),
                (
                    "scheme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="mutual_funds.mutualfundscheme",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
