# Generated by Django 5.2.6 on 2025-09-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mutual_funds", "0003_mutualfundperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutualfundscheme",
            name="aum",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Assets Under Management in Crores",
                max_digits=20,
                null=True,
            ),
        ),
    ]
